// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WhatsAppMonitorAssistant.Modules.Messaging.Infrastructure.Persistence;

#nullable disable

namespace WhatsAppMonitorAssistant.Modules.Messaging.Infrastructure.Migrations
{
    [DbContext(typeof(MessagingDbContext))]
    partial class MessagingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("messaging")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WhatsAppMonitorAssistant.Modules.Messaging.Domain.InboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempts");

                    b.Property<string>("Body")
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTime?>("ClaimedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at");

                    b.Property<long?>("ConversationId")
                        .HasColumnType("bigint")
                        .HasColumnName("conversation_id");

                    b.Property<string>("CustomerExternalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("customer_external_id");

                    b.Property<long>("EnvelopeId")
                        .HasColumnType("bigint")
                        .HasColumnName("envelope_id");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_type");

                    b.Property<string>("PartitionKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("partition_key");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending")
                        .HasColumnName("processing_status");

                    b.Property<string>("ProviderMessageId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider_message_id");

                    b.Property<DateTime>("ProviderTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("provider_timestamp");

                    b.Property<DateTime>("ReceivedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("RunAfter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("run_after")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("EnvelopeId")
                        .HasDatabaseName("ix_inbox_message_envelope");

                    b.HasIndex("ProviderMessageId")
                        .IsUnique();

                    b.HasIndex("RunAfter", "Id")
                        .HasDatabaseName("ix_inbox_claim")
                        .HasFilter("processing_status = 'Pending'");

                    b.ToTable("inbox_message", "messaging", t =>
                        {
                            t.HasCheckConstraint("ck_inbox_status", "processing_status IN ('Pending','Claimed','Processed','Failed','DeadLettered')");
                        });
                });

            modelBuilder.Entity("WhatsAppMonitorAssistant.Modules.Messaging.Domain.OutboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempts");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<byte[]>("BodyHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("body_hash");

                    b.Property<DateTime?>("ClaimedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at");

                    b.Property<long>("ConversationId")
                        .HasColumnType("bigint")
                        .HasColumnName("conversation_id");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CustomerExternalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("customer_external_id");

                    b.Property<string>("DeliveryStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending")
                        .HasColumnName("delivery_status");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<int>("MaxAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5)
                        .HasColumnName("max_attempts");

                    b.Property<string>("PartitionKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("partition_key");

                    b.Property<string>("ProviderMessageId")
                        .HasColumnType("text")
                        .HasColumnName("provider_message_id");

                    b.Property<DateTime>("RunAfter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("run_after")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("AI")
                        .HasColumnName("sender");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.HasKey("Id");

                    b.HasIndex("ProviderMessageId")
                        .IsUnique();

                    b.HasIndex("RunAfter", "Id")
                        .HasDatabaseName("ix_outbox_claim")
                        .HasFilter("delivery_status = 'Pending'");

                    b.ToTable("outbox_message", "messaging", t =>
                        {
                            t.HasCheckConstraint("ck_outbox_body_hash", "body_hash = sha256(body::bytea)");

                            t.HasCheckConstraint("ck_outbox_sender", "sender IN ('AI','Agent','System')");

                            t.HasCheckConstraint("ck_outbox_status", "delivery_status IN ('Pending','Claimed','Sent','Failed','DeadLettered')");
                        });
                });

            modelBuilder.Entity("WhatsAppMonitorAssistant.Modules.Messaging.Domain.WebhookEnvelope", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<byte[]>("EnvelopeHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("envelope_hash");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("RawBody")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_body");

                    b.Property<DateTime>("ReceivedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("EnvelopeHash")
                        .IsUnique();

                    b.ToTable("webhook_envelope", "messaging");
                });

            modelBuilder.Entity("WhatsAppMonitorAssistant.Modules.Messaging.Domain.InboxMessage", b =>
                {
                    b.HasOne("WhatsAppMonitorAssistant.Modules.Messaging.Domain.WebhookEnvelope", "Envelope")
                        .WithMany()
                        .HasForeignKey("EnvelopeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Envelope");
                });
#pragma warning restore 612, 618
        }
    }
}
