<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Testcontainers.PostgreSql" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Host.Web/Host.Web.csproj" />
    <ProjectReference Include="../../src/Modules/Catalog/Catalog.csproj" />
    <ProjectReference Include="../../src/Modules/Conversations/Conversations.csproj" />
    <ProjectReference Include="../../src/Modules/Identity/Identity.csproj" />
    <ProjectReference Include="../../src/Modules/Messaging/Messaging.csproj" />
    <ProjectReference Include="../../src/Modules/Storefront/Storefront.csproj" />
    <ProjectReference Include="../../tools/DemoOps/DemoOps.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
