<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>WhatsAppMonitorAssistant.Modules.Identity</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../BuildingBlocks/Application/BuildingBlocks.Application.csproj" />
    <ProjectReference Include="../../BuildingBlocks/Domain/BuildingBlocks.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

</Project>
