<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../../BuildingBlocks/Application/BuildingBlocks.Application.csproj" />
    <ProjectReference Include="../../BuildingBlocks/Domain/BuildingBlocks.Domain.csproj" />
    <ProjectReference Include="../../BuildingBlocks/Messaging/BuildingBlocks.Messaging.csproj" />
  </ItemGroup>

</Project>
