// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WhatsAppMonitorAssistant.Modules.Catalog.Infrastructure.Persistence;

#nullable disable

namespace WhatsAppMonitorAssistant.Modules.Catalog.Infrastructure.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260917132014_InitialCatalog")]
    partial class InitialCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WhatsAppMonitorAssistant.Modules.Catalog.Domain.CatalogAuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long?>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.Property<string>("NewJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_json");

                    b.Property<string>("OldJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_json");

                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("audit_log", "catalog");
                });

            modelBuilder.Entity("WhatsAppMonitorAssistant.Modules.Catalog.Domain.ProductModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("brand");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<string>("ModelCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model_code");

                    b.Property<string>("PanelType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("panel_type");

                    b.Property<int>("RefreshRate")
                        .HasColumnType("integer")
                        .HasColumnName("refresh_rate");

                    b.Property<int>("ResolutionHeight")
                        .HasColumnType("integer")
                        .HasColumnName("resolution_height");

                    b.Property<int>("ResolutionWidth")
                        .HasColumnType("integer")
                        .HasColumnName("resolution_width");

                    b.PrimitiveCollection<List<string>>("SearchTags")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("search_tags")
                        .HasDefaultValueSql("'{}'::text[]");

                    b.Property<decimal>("SizeInches")
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("size_inches");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("ModelCode")
                        .IsUnique();

                    b.ToTable("product_model", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_model_panel", "panel_type IN ('IPS','TN','VA','OLED','Other')");

                            t.HasCheckConstraint("ck_model_refresh", "refresh_rate BETWEEN 24 AND 500");

                            t.HasCheckConstraint("ck_model_resolution", "resolution_width > 0 AND resolution_height > 0");

                            t.HasCheckConstraint("ck_model_size", "size_inches BETWEEN 10 AND 60");
                        });
                });

            modelBuilder.Entity("WhatsAppMonitorAssistant.Modules.Catalog.Domain.ProductModelPort", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<int>("Count")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("count");

                    b.Property<string>("PortType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("port_type");

                    b.Property<long>("ProductModelId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_model_id");

                    b.HasKey("Id");

                    b.HasIndex("ProductModelId")
                        .HasDatabaseName("ix_model_port_model");

                    b.HasIndex("ProductModelId", "PortType")
                        .IsUnique()
                        .HasDatabaseName("uq_model_port");

                    b.ToTable("product_model_port", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_port_count", "count BETWEEN 1 AND 16");
                        });
                });

            modelBuilder.Entity("WhatsAppMonitorAssistant.Modules.Catalog.Domain.ProductVariant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("CosmeticNotes")
                        .HasColumnType("text")
                        .HasColumnName("cosmetic_notes");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("grade");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<long>("ProductModelId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_model_id");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("quantity");

                    b.Property<decimal>("SellingPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("selling_price");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sku");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("WarrantyDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("warranty_days");

                    b.Property<string>("WarrantyNotes")
                        .HasColumnType("text")
                        .HasColumnName("warranty_notes");

                    b.HasKey("Id");

                    b.HasIndex("ProductModelId")
                        .HasDatabaseName("ix_variant_model");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.HasIndex("ProductModelId", "Grade")
                        .IsUnique()
                        .HasDatabaseName("uq_variant_model_grade");

                    b.ToTable("product_variant", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_variant_grade", "grade IN ('A','B','C')");

                            t.HasCheckConstraint("ck_variant_price", "selling_price >= 0");

                            t.HasCheckConstraint("ck_variant_quantity", "quantity >= 0");

                            t.HasCheckConstraint("ck_variant_warranty", "warranty_days >= 0");
                        });
                });

            modelBuilder.Entity("WhatsAppMonitorAssistant.Modules.Catalog.Domain.ProductModelPort", b =>
                {
                    b.HasOne("WhatsAppMonitorAssistant.Modules.Catalog.Domain.ProductModel", "ProductModel")
                        .WithMany("Ports")
                        .HasForeignKey("ProductModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductModel");
                });

            modelBuilder.Entity("WhatsAppMonitorAssistant.Modules.Catalog.Domain.ProductVariant", b =>
                {
                    b.HasOne("WhatsAppMonitorAssistant.Modules.Catalog.Domain.ProductModel", "ProductModel")
                        .WithMany("Variants")
                        .HasForeignKey("ProductModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductModel");
                });

            modelBuilder.Entity("WhatsAppMonitorAssistant.Modules.Catalog.Domain.ProductModel", b =>
                {
                    b.Navigation("Ports");

                    b.Navigation("Variants");
                });
#pragma warning restore 612, 618
        }
    }
}
