// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WhatsAppMonitorAssistant.Modules.Conversations.Infrastructure.Persistence;

#nullable disable

namespace WhatsAppMonitorAssistant.Modules.Conversations.Infrastructure.Migrations
{
    [DbContext(typeof(ConversationDbContext))]
    partial class ConversationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("conversations")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WhatsAppMonitorAssistant.Modules.Conversations.Domain.Conversation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<DateTime?>("LastInboundAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_inbound_at");

                    b.Property<DateTime?>("LastOutboundAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_outbound_at");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("AI")
                        .HasColumnName("mode");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("WindowExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_expires_at");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique()
                        .HasDatabaseName("ux_conversation_open_customer")
                        .HasFilter("mode <> 'Closed'");

                    b.ToTable("conversation", "conversations", t =>
                        {
                            t.HasCheckConstraint("ck_conversation_mode", "mode IN ('AI','Human','Closed')");
                        });
                });

            modelBuilder.Entity("WhatsAppMonitorAssistant.Modules.Conversations.Domain.ConversationState", b =>
                {
                    b.Property<long>("ConversationId")
                        .HasColumnType("bigint")
                        .HasColumnName("conversation_id");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("StateJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("state_json")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("ConversationId");

                    b.ToTable("conversation_state", "conversations");
                });

            modelBuilder.Entity("WhatsAppMonitorAssistant.Modules.Conversations.Domain.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<DateTime>("FirstSeenAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("LastSeenAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("WhatsappNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("whatsapp_number");

                    b.HasKey("Id");

                    b.HasIndex("WhatsappNumber")
                        .IsUnique();

                    b.ToTable("customer", "conversations");
                });

            modelBuilder.Entity("WhatsAppMonitorAssistant.Modules.Conversations.Domain.Conversation", b =>
                {
                    b.HasOne("WhatsAppMonitorAssistant.Modules.Conversations.Domain.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("WhatsAppMonitorAssistant.Modules.Conversations.Domain.ConversationState", b =>
                {
                    b.HasOne("WhatsAppMonitorAssistant.Modules.Conversations.Domain.Conversation", "Conversation")
                        .WithOne("State")
                        .HasForeignKey("WhatsAppMonitorAssistant.Modules.Conversations.Domain.ConversationState", "ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("WhatsAppMonitorAssistant.Modules.Conversations.Domain.Conversation", b =>
                {
                    b.Navigation("State");
                });
#pragma warning restore 612, 618
        }
    }
}
